### ISSUE TITLE
Respond to https://github.com/jenkinsci/config-rotator-plugin/pull/1

### ISSUE THREAD

**Issue by buep** [Praqma/config-rotator-plugin#12]
We got a PR on https://github.com/jenkinsci/config-rotator-plugin/pull/1

Please respond @MadsNielsen when you get to work with the CR plugin next time.

**Comment by praqma-thi** [comment]
I merged that one in on our Praqma config rotator a while ago. I'll see to wrapping this up proper.

**Comment by praqma-thi** [comment]
Decided to make a new release for CR, and push that to the Jenkins repo. 
Have to fix the pipeline first though, as nightcrawler is down (read: gone).
Currently restoring nightcrawler from backup. 
Interesting day so far.

**Comment by praqma-thi** [comment]
Nightcrawler has been revived, the license server restored, had to tweak the license manager, but it's up and running now.

Running the pipeline of CR now, let's see how far we get!

**Comment by praqma-thi** [comment]
Release made, had to manually sync the praqma and jenkinsci repository. Still have to figure out how to fix this. Going to reply on the PR now

**Comment by praqma-thi** [comment]
Forgot to close this after I did.
