### ISSUE TITLE
Config Rotator does not release all file handles when used on windows with git

### ISSUE THREAD

**Issue by RandomSort** [Praqma/config-rotator-plugin#9]
With a config rotator job it is not possible to wipe the workspace due to config rotator for some reason not "letting go" of files in the .git folder of the workspace.

This happens at least on windows with git repositories.

**Comment by MadsNielsen** [comment]
Timeboxed (4 hours)

- [ ] Check that `repository.close()` is called when needed
- [ ] Look for bugs in JGit
- [ ] Update to newer JGit
